# =========================================
# railway.toml  (repo root)
# =========================================
[services.web]
builder = "Dockerfile"
healthcheckPath = "/api/health"
healthcheckTimeout = 120000